'use client';

import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { createBrowserClient } from '@supabase/ssr';

export default function CallbackPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  
  useEffect(() => {
    const handleCallback = async () => {
      // If Supabase API returned an error parameter, display it
      const errorParam = searchParams.get('error');
      if (errorParam) {
        setErrorMsg(errorParam.replace(/_/g, ' '));
        return;
      }

      // Check for PKCE code or token_hash in URL params
      const code = searchParams.get('code');
      const token_hash = searchParams.get('token_hash');
      const type = searchParams.get('type');
      
      // If we have token_hash or code, redirect to our secure API route
      if (token_hash && type) {
         window.location.href = `/api/auth/confirm?token_hash=${token_hash}&type=${type}`;
         return;
      }
      
      if (code) {
         window.location.href = `/api/auth/confirm?code=${code}`;
         return;
      }

      // If no search params, it might be an Implicit Flow hash (#access_token) generated by Dashboard 
      // Supabase createBrowserClient automatically parses it and sets the session cookies.
      const supabase = createBrowserClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
      );
      
      // First try to grab the session immediately
      const { data: { session } } = await supabase.auth.getSession();
      
      if (session) {
        router.push('/set-password');
        return;
      }
      
      // If we still have no session, wait just a moment for async hash parsing
      setTimeout(async () => {
        const { data: { session: delayedSession } } = await supabase.auth.getSession();
        if (delayedSession) {
          router.push('/set-password');
        } else {
          setErrorMsg("Verification failed, invalid token, or link expired. Please try again.");
        }
      }, 1000);
    };
    
    handleCallback();
  }, [router, searchParams]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
      <div className="max-w-md w-full p-8 bg-white dark:bg-gray-800 shadow rounded-lg text-center">
        {errorMsg ? (
          <div>
            <h2 className="text-xl font-bold text-red-600 mb-4">Verification Error</h2>
            <p className="text-gray-600 dark:text-gray-300 mb-6">{errorMsg}</p>
            <button 
              onClick={() => router.push('/login')}
              className="px-4 py-2 bg-primary text-white rounded-md hover:bg-primary-dark"
            >
              Back to Login
            </button>
          </div>
        ) : (
          <div>
            <div className="mb-4 inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            <h2 className="text-xl font-bold text-gray-800 dark:text-white mb-2">Verifying...</h2>
            <p className="text-gray-600 dark:text-gray-300 text-sm">
              Please wait while we securely authenticate your invitation.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
